-- Thêm dữ liệu vào bảng admin
INSERT INTO admin (username, password, created_date, updated_date, status)
VALUES ('admin1', 'hashed_password_1', NOW(), NULL, 'ACTIVE'),
       ('admin2', 'hashed_password_2', NOW(), NULL, 'INACTIVE'),
       ('admin3', 'hashed_password_3', NOW(), NULL, 'ACTIVE'),
       ('admin4', 'hashed_password_4', NOW(), NULL, 'INACTIVE'),
       ('admin5', 'hashed_password_5', NOW(), NULL, 'ACTIVE');

-- Thêm dữ liệu vào bảng user
INSERT INTO user (username, password, created_date, updated_date, status, nickname)
VALUES ('NguyenVanK', 'hashed_password_13', NOW(), NULL, 'ACTIVE', 'NVK'),
       ('TranThiL', 'hashed_password_14', NOW(), NULL, 'INACTIVE', 'TTL'),
       ('LeVanH', 'hashed_password_15', NOW(), NULL, 'ACTIVE', 'LVH'),
       ('PhamThiP', 'hashed_password_16', NOW(), NULL, 'INACTIVE', 'PTP'),
       ('DangThiO', 'hashed_password_17', NOW(), NULL, 'ACTIVE', 'DTO'),
       ('DangTranF', 'hashed_password_18', NOW(), NULL, 'INACTIVE', 'DTF'),
       ('PhamNhuP', 'hashed_password_19', NOW(), NULL, 'ACTIVE', 'PNP'),
       ('LamVanN', 'hashed_password_20', NOW(), NULL, 'INACTIVE', 'LVN'),
       ('VuThiT', 'hashed_password_21', NOW(), NULL, 'ACTIVE', 'VTT'),
       ('ThieuDinhN', 'hashed_password_22', NOW(), NULL, 'INACTIVE', 'TDN');

-- Thêm dữ liệu vào bảng fullname
INSERT INTO fullname (first_name, mid_name, last_name, status, created_date, updated_date, user_id)
VALUES ('Khánh', 'Văn', 'Nguyễn', 'ACTIVE', NOW(), NULL, 1),
       ('Linh', 'Thị', 'Trần', 'ACTIVE', NOW(), NULL, 2),
       ('Hậu', 'Văn', 'Lê', 'ACTIVE', NOW(), NULL, 3),
       ('Phương', 'Thị', 'Phạm', 'ACTIVE', NOW(), NULL, 4),
       ('Oanh', 'Thị', 'Đặng', 'ACTIVE', NOW(), NULL, 5),
       ('Phong', 'Trần', 'Đặng', 'ACTIVE', NOW(), NULL, 6),
       ('Phương', 'Như', 'Phạm', 'ACTIVE', NOW(), NULL, 7),
       ('Nam', 'Văn', 'Lâm', 'ACTIVE', NOW(), NULL, 8),
       ('Thảo', 'Thị', 'Vũ', 'ACTIVE', NOW(), NULL, 9),
       ('Nam', 'Đình', 'Thiều', 'ACTIVE', NOW(), NULL, 10);

-- Thêm dữ liệu vào bảng address
INSERT INTO address (country, city, district, street, address_detail)
VALUES ('Việt Nam', 'Hà Nội', 'Ba Đình', 'Phố Kim Mã', 'Số 123'),
       ('Việt Nam', 'Hồ Chí Minh', 'Quận 1', 'Đường Nguyễn Huệ', 'Tòa nhà Bitexco'),
       ('Việt Nam', 'Đà Nẵng', 'Hải Châu', 'Đường Bạch Đằng', 'Số 45'),
       ('Việt Nam', 'Cần Thơ', 'Ninh Kiều', 'Đường Hòa Bình', 'Số 22'),
       ('Việt Nam', 'Hải Phòng', 'Ngô Quyền', 'Đường Lạch Tray', 'Số 68'),
       ('Việt Nam', 'Hà Nội', 'Hoàn Kiếm', 'Phố Hàng Ngang', 'Số 18A'),
       ('Việt Nam', 'Hồ Chí Minh', 'Quận 3', 'Đường Điện Biên Phủ', 'Chung cư Sài Gòn Pearl'),
       ('Việt Nam', 'Nha Trang', 'Lộc Thọ', 'Đường Trần Phú', 'Resort Vinpearl'),
       ('Việt Nam', 'Huế', 'Thành phố Huế', 'Đường Lê Lợi', 'Khách sạn Mường Thanh'),
       ('Việt Nam', 'Vũng Tàu', 'Thành phố Vũng Tàu', 'Đường Thùy Vân', 'Số 52');

-- Thêm dữ liệu vào bảng user_address
INSERT INTO user_address (user_id, address_id)
VALUES (1, 1),
       (2, 2),
       (3, 3),
       (4, 4),
       (5, 5),
       (6, 6),
       (7, 7),
       (8, 8),
       (9, 9),
       (10, 10);

-- Thêm dữ liệu vào bảng teacher
INSERT INTO teacher (name, username, password, created_date, updated_date, status)
VALUES ('Mr.Nguyễn Văn X', 'mr_NguyenVanX', 'hashed_password_6', NOW(), NULL, 'ACTIVE'),
       ('Ms.Trần Thị Y', 'ms_TranThiY', 'hashed_password_7', NOW(), NULL, 'INACTIVE'),
       ('Mr.Lê Văn Z', 'mr_LeVanZ', 'hashed_password_8', NOW(), NULL, 'ACTIVE'),
       ('Ms.Phạm Thị Q', 'ms_PhamThiQ', 'hashed_password_9', NOW(), NULL, 'INACTIVE'),
       ('Mr.Đặng Văn M', 'mr_DangVanM', 'hashed_password_10', NOW(), NULL, 'ACTIVE'),
       ('Mr.Hồ Văn P', 'mr_HoVanP', 'hashed_password_11', NOW(), NULL, 'INACTIVE'),
       ('Ms.Nguyễn Thị H', 'ms_NguyenThiH', 'hashed_password_12', NOW(), NULL, 'ACTIVE');

-- Thêm dữ liệu vào bảng course
INSERT INTO course (name, description, status, created_date, updated_date, teacher_id)
VALUES ('Toán học', 'Khóa học về đại số và hình học', 'ACTIVE', NOW(), NULL, 1),
       ('Vật lý', 'Khóa học về các định luật vật lý', 'ACTIVE', NOW(), NULL, 2),
       ('Lịch sử', 'Khóa học về các sự kiện lịch sử quan trọng', 'ACTIVE', NOW(), NULL, 3),
       ('Hóa học', 'Khóa học về các phản ứng hóa học', 'ACTIVE', NOW(), NULL, 4),
       ('Sinh học', 'Khóa học về cấu trúc và chức năng của sinh vật', 'ACTIVE', NOW(), NULL, 5),
       ('Nhập môn lập trình', 'Khóa học về lập trình cơ bản', 'ACTIVE', NOW(), NULL, 6),
       ('Lập trình hướng đối tượng', 'Khóa học về phương pháp lập trình hướng đối tượng', 'ACTIVE', NOW(), NULL, 6),
       ('Phương pháp nghiên cứu khoa học', 'Khóa học về cách thức thực hiện nghiên cứu khoa học', 'ACTIVE', NOW(), NULL, 7);

-- Thêm dữ liệu vào bảng student_course
INSERT INTO user_course (user_id, course_id, rating, review, status, created_date, updated_date)
VALUES (1, 1, 5, 'Great course! Very informative.', 'PROCESSING', NOW(), NULL),
       (2, 2, 4, 'Good introduction, but could use more examples.', 'PROCESSING', NOW(), NULL),
       (3, 3, 3, 'Decent course, but not engaging.', 'START', NOW(), NULL),
       (4, 4, 5, 'Great course! Very informative.', 'PROCESSING', NOW(), NULL),
       (5, 5, 4, 'Good introduction, but could use more examples.', 'PROCESSING', NOW(), NULL),
       (1, 6, 3, 'Decent course, but not engaging.', 'PROCESSING', NOW(), NULL),
       (2, 7, 5, 'Great course! Very informative.', 'START', NOW(), NULL),
       (3, 8, 4, 'Good introduction, but could use more examples.', 'PROCESSING', NOW(), NULL),
       (6, 7, 3, 'Decent course, but not engaging.', 'START', NOW(), NULL),
       (7, 6, 5, 'Great course! Very informative.', 'DONE', NOW(), NULL),
       (8, 5, 4, 'Good introduction, but could use more examples.', 'PROCESSING', NOW(), NULL),
       (9, 6, 3, 'Decent course, but not engaging.', 'DONE', NOW(), NULL),
       (10, 7, 5, 'Great course! Very informative.', 'PROCESSING', NOW(), NULL),
       (1, 8, 4, 'Good introduction, but could use more examples.', 'DONE', NOW(), NULL);

-- Thêm dữ liệu vào bảng chapter
INSERT INTO chapter (name, description, status, `order`, created_date, updated_date, course_id)
VALUES ('Đại số cơ bản', 'Giới thiệu về đại số', 'ACTIVE', 1, NOW(), NULL, 1),
       ('Hình học cơ bản', 'Các hình khối và công thức tính', 'ACTIVE', 1, NOW(), NULL, 1),
       ('Cơ học cổ điển', 'Các định luật chuyển động của Newton', 'ACTIVE', 1, NOW(), NULL, 2),
       ('Nhiệt học', 'Nguyên lý cơ bản về nhiệt động lực học', 'ACTIVE', 1, NOW(), NULL, 2),
       ('Chiến tranh thế giới thứ hai', 'Tổng quan các sự kiện lớn', 'ACTIVE', 1, NOW(), NULL, 3),
       ('Cách mạng Pháp', 'Nguyên nhân và diễn biến', 'ACTIVE', 1, NOW(), NULL, 3),
       ('Liên kết hóa học', 'Giới thiệu về liên kết hóa học', 'ACTIVE', 1, NOW(), NULL, 4),
       ('Phản ứng hóa học', 'Các loại phản ứng', 'ACTIVE', 1, NOW(), NULL, 4),
       ('Sinh học tế bào', 'Cấu trúc của tế bào', 'ACTIVE', 1, NOW(), NULL, 5),
       ('Di truyền học', 'Cơ chế di truyền','ACTIVE', 1, NOW(), NULL, 5),
       ('Lập trình C++', 'Cách lập trình sử dụng ngôn ngữ C++', 'ACTIVE', 1, NOW(), NULL, 6),
       ('Kỹ thuật lập trình', 'Con trỏ trong C++, ứng dụng vào CTDL và thuật toán', 'ACTIVE', 1, NOW(), NULL, 6),
       ('Giới thiệu về lập trình OOP', 'Các tính chất cơ bản của OOP', 'ACTIVE', 1, NOW(), NULL, 7),
       ('Bài tập lớn', 'Ứng dụng OOP vào các bài toán thực tế', 'ACTIVE', 1, NOW(), NULL, 7),
       ('Kỹ năng viết bài báo nghiên cứu khoa học', 'Học các kỹ thuật để viết được một bài báo khoa học', 'ACTIVE', 1, NOW(), NULL, 8),
       ('Các format bài báo cáo khoa học chính', 'Giới thiệu về các loại báo cáo khoa học', 'ACTIVE', 1, NOW(), NULL, 8);

-- Thêm dữ liệu vào bảng lesson
INSERT INTO lesson (name, description, status, type, url, `order`, created_date, updated_date, chapter_id)
VALUES ('Phương trình bậc nhất', 'Giải phương trình bậc nhất', 'ACTIVE', 'video', 'http://first-degree-equation.com/', 1,
        NOW(), NULL, 1),
       ('Phương trình bậc hai', 'Giải phương trình bậc hai', 'ACTIVE', 'video', 'http://quadratic-equation.com/', 1,
        NOW(), NULL, 1),
       ('Ma trận', 'Các phép toán với ma trận', 'ACTIVE', 'video', 'http://matrix.com/', 1,
        NOW(), NULL, 1),
       ('Đường tròn', 'Cách vẽ và tính các đại lượng liên quan đến đường tròn', 'ACTIVE', 'video', 'http://circle.com/', 1,
        NOW(), NULL, 2),
       ('Đa giác', 'Phân biệt các hình và tính diện tích đa giác', 'ACTIVE', 'video', 'http://polygon.com/', 1,
        NOW(), NULL, 2),
       ('Lực và chuyển động', 'Hiểu về lực', 'ACTIVE', 'video', 'http://force-and-motion.com/', 1,
        NOW(), NULL, 3),
       ('Năng lượng nhiệt', 'Hiểu về nhiệt và năng lượng', 'ACTIVE', 'video', 'http://thermal-energy.com/', 1,
        NOW(), NULL, 4),
       ('Trận Stalingrad', 'Trận chiến quan trọng trong Thế chiến thứ hai', 'ACTIVE', 'video', 'http://stalingrad-battle.com/', 1,
        NOW(), NULL, 5),
       ('Cách mạng tháng 7', 'Sự kiện quan trọng trong cách mạng Pháp', 'ACTIVE', 'video', 'http://july-revolution.com/', 1,
        NOW(), NULL, 6),
       ('Liên kết ion', 'Giới thiệu về liên kết ion', 'ACTIVE', 'video', 'http://ionic-bond.com/', 1,
        NOW(), NULL, 7),
       ('Phản ứng oxy hóa', 'Các phản ứng hóa học với oxy', 'ACTIVE', 'video', 'http://oxidation-reaction.com/', 1,
        NOW(), NULL, 8),
       ('Màng tế bào', 'Chức năng của màng tế bào', 'ACTIVE', 'video', 'http://cell-membrance.com/', 1,
        NOW(), NULL, 9),
       ('DNA và RNA', 'Các cơ chế di truyền liên quan đến DNA và RNA', 'ACTIVE', 'video', 'http://dna-rna.com/', 1,
        NOW(), NULL, 10),
       ('Biến và kiểu dữ liệu', 'Giới thiệu và cách dùng biến và các kiểu dữ liệu trong C++', 'ACTIVE', 'video', 'http://types-and-variables/', 1,
        NOW(), NULL, 11),
       ('Các phép toán trong lập trình', 'Giới thiệu các phép toán và toán tử trong C++', 'ACTIVE', 'video', 'http://operator/', 1,
        NOW(), NULL, 11),
       ('Hàm', 'Cách tạo các hàm trong C++', 'ACTIVE', 'video', 'http://function.com/', 1,
        NOW(), NULL, 11),
       ('Vòng lặp', 'Giới thiệu và cách dùng vòng lặp trong C++', 'ACTIVE', 'video', 'http://loop.com/', 1,
        NOW(), NULL, 11),
       ('Câu điều kiện', 'Giới thiệu và cách dùng câu điều kiện trong C++', 'ACTIVE', 'video', 'http://conditional-statement.com/', 1,
        NOW(), NULL, 11),
       ('Con trỏ', 'Giới thiệu về con trỏ trong C++ và bộ nhớ máy tính', 'ACTIVE', 'video', 'http://pointer.com/', 1,
        NOW(), NULL, 12),
       ('Cấu trúc dữ liệu', 'Giới thiệu cấu trúc dữ liệu cơ bản', 'ACTIVE', 'video', 'http://data-structures.com/', 1,
        NOW(), NULL, 12),
       ('Thuật toán', 'Giới thiệu một số thuật toán sắp xếp và tìm kiếm cơ bản', 'ACTIVE', 'video', 'http://algorithms.com/', 1,
        NOW(), NULL, 12),
       ('Tính kế thừa', 'Giới thiệu về tính kế thừa trong OOP', 'ACTIVE', 'video', 'http://inheritance.com/', 1,
        NOW(), NULL, 13),
       ('Tính trừu tượng', 'Giới thiệu tính trừu tượng trong OOP', 'ACTIVE', 'video', 'http://abtraction.com/', 1,
        NOW(), NULL, 13),
       ('Tính đóng gói', 'Giới thiệu về tính đóng gói trong OOP', 'ACTIVE', 'video', 'http://encapsulation.com/', 1,
        NOW(), NULL, 13),
       ('Tính đa hình', 'Giới thiệu về tính đa hình trong OOP', 'ACTIVE', 'video', 'http://polymorphism.com/', 1,
        NOW(), NULL, 13),
       ('Các chủ đề bài tập lớn', 'Chọn và làm một trong các chủ đề OOP', 'ACTIVE', 'video', 'http://oop-project-topics.com/', 1,
        NOW(), NULL, 14),
       ('Bố cục bài báo cáo khoa học', 'Giới thiệu bố cục bài báo cáo khoa học', 'ACTIVE', 'video', 'http://sciene-report-structure.com/', 1,
        NOW(), NULL, 15),
       ('Abstract', 'Cách viết phần abstract', 'ACTIVE', 'video', 'http://how-to-write-abtract.com/', 1,
        NOW(), NULL, 15),
       ('Introduction', 'Cách viết introduction', 'ACTIVE', 'video', 'http://how-to-write-introduction.com/', 1,
        NOW(), NULL, 15),
       ('Reference', 'Cách viết reference và cách trích dẫn tài liệu', 'ACTIVE', 'video', 'http://how-to-write-reference.com/', 1,
        NOW(), NULL, 15),
       ('APA style', 'Giới thiệu format APA', 'ACTIVE', 'video', 'http://apa-style.com/', 1,
        NOW(), NULL, 16),
       ('MLA style', 'Giới thiệu format MLA', 'ACTIVE', 'video', 'http://mla-style.com/', 1,
        NOW(), NULL, 16),
       ('Havard style', 'Giới thiệu format Havard', 'ACTIVE', 'video', 'http://havard-style.com/', 1,
        NOW(), NULL, 16);

-- Thêm dữ liệu vào bảng student_course_lesson
INSERT INTO user_course_lesson (user_id, course_id, lesson_id, status, created_date, updated_date)
VALUES (1, 1, 1, 'DONE', NOW(), NULL),
       (1, 1, 2, 'PROCESSING', NOW(), NULL),
       (1, 1, 3, 'START', NOW(), NULL),
       (1, 1, 4, 'START', NOW(), NULL),
       (1, 1, 5, 'START', NOW(), NULL),
       (2, 2, 6, 'START', NOW(), NULL),
       (2, 2, 7, 'START', NOW(), NULL),
       (3, 3, 8, 'START', NOW(), NULL),
       (3, 3, 9, 'START', NOW(), NULL),
       (4, 4, 10, 'PROCESSING', NOW(), NULL),
       (4, 4, 11, 'START', NOW(), NULL),
       (5, 5, 12, 'PROCESSING', NOW(), NULL),
       (5, 5, 13, 'START', NOW(), NULL),
       (1, 6, 14, 'DONE', NOW(), NULL),
       (1, 6, 15, 'DONE', NOW(), NULL),
       (1, 6, 16, 'DONE', NOW(), NULL),
       (1, 6, 17, 'DONE', NOW(), NULL),
       (1, 6, 18, 'PROCESSING', NOW(), NULL),
       (1, 6, 19, 'START', NOW(), NULL),
       (1, 6, 20, 'START', NOW(), NULL),
       (1, 6, 21, 'START', NOW(), NULL),
       (2, 7, 22, 'START', NOW(), NULL),
       (2, 7, 23, 'START', NOW(), NULL),
       (2, 7, 24, 'START', NOW(), NULL),
       (2, 7, 25, 'START', NOW(), NULL),
       (2, 7, 26, 'START', NOW(), NULL),
       (3, 8, 27, 'DONE', NOW(), NULL),
       (3, 8, 28, 'DONE', NOW(), NULL),
       (3, 8, 29, 'PROCESSING', NOW(), NULL),
       (3, 8, 30, 'START', NOW(), NULL),
       (3, 8, 31, 'START', NOW(), NULL),
       (3, 8, 32, 'START', NOW(), NULL),
       (3, 8, 33, 'START', NOW(), NULL),
       (6, 7, 22, 'START', NOW(), NULL),
       (6, 7, 23, 'START', NOW(), NULL),
       (6, 7, 24, 'START', NOW(), NULL),
       (6, 7, 25, 'START', NOW(), NULL),
       (6, 7, 26, 'START', NOW(), NULL),
       (7, 6, 14, 'DONE', NOW(), NULL),
       (7, 6, 15, 'DONE', NOW(), NULL),
       (7, 6, 16, 'DONE', NOW(), NULL),
       (7, 6, 17, 'DONE', NOW(), NULL),
       (7, 6, 18, 'DONE', NOW(), NULL),
       (7, 6, 19, 'DONE', NOW(), NULL),
       (7, 6, 20, 'DONE', NOW(), NULL),
       (7, 6, 21, 'DONE', NOW(), NULL),
       (8, 5, 12, 'DONE', NOW(), NULL),
       (8, 5, 13, 'PROCESSING', NOW(), NULL),
       (9, 6, 14, 'DONE', NOW(), NULL),
       (9, 6, 15, 'DONE', NOW(), NULL),
       (9, 6, 16, 'DONE', NOW(), NULL),
       (9, 6, 17, 'DONE', NOW(), NULL),
       (9, 6, 18, 'DONE', NOW(), NULL),
       (9, 6, 19, 'DONE', NOW(), NULL),
       (9, 6, 20, 'DONE', NOW(), NULL),
       (9, 6, 21, 'DONE', NOW(), NULL),
       (10, 7, 22, 'DONE', NOW(), NULL),
       (10, 7, 23, 'DONE', NOW(), NULL),
       (10, 7, 24, 'DONE', NOW(), NULL),
       (10, 7, 25, 'PROCESSING', NOW(), NULL),
       (10, 7, 26, 'PROCESSING', NOW(), NULL),
       (1, 8, 27, 'DONE', NOW(), NULL),
       (1, 8, 28, 'DONE', NOW(), NULL),
       (1, 8, 29, 'DONE', NOW(), NULL),
       (1, 8, 30, 'DONE', NOW(), NULL),
       (1, 8, 31, 'DONE', NOW(), NULL),
       (1, 8, 32, 'DONE', NOW(), NULL),
       (1, 8, 33, 'DONE', NOW(), NULL);