server:
  port: 8081

spring:
  application:
    name: e-learn

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/e_learn
    username: root
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
